name: Sync Upstream Repository

on:
  schedule:
    - cron: '*/2 * * * *'  # Runs every 5 minutes
  push:
    branches:
      - main  # Replace with your branch if it's different

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/Vishu-Organization/FlavorHive.git

      - name: Fetch Upstream Changes
        run: git fetch upstream

      - name: Merge Upstream Changes into your Branch (with automatic conflict resolution)
        run: |
          git checkout main
          git merge upstream/main -X theirs --allow-unrelated-histories  # Allow unrelated histories and automatically resolve conflicts by keeping upstream changes

      - name: Push Changes to Your Repository
        run: git push origin main

      - name: Create a Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          gh pr create --base main --head main --title "Sync with upstream" --body "Automatically synced with upstream repo"
