name: Auto-Sync Fork

on:
  schedule:
    - cron: "*/5 * * * *" # Run every 12 hours
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    # Checkout the forked repository
    - name: Checkout Fork Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Configure Git to set user name and email for commits
    - name: Configure Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"

    # Add upstream repository and fetch changes
    - name: Add Upstream Repository
      run: |
        if ! git remote | grep -q upstream; then
          git remote add upstream https://github.com/Vishu-Organization/FlavorHive
        fi
        git fetch upstream

    # Create a new branch and merge changes from upstream
    - name: Create Branch for Upstream Changes
      run: |
        git checkout -B update-from-upstream
        git merge upstream/main --no-edit --allow-unrelated-histories --strategy=recursive --strategy-option=theirs || echo "Merge conflict handled or no changes."

        if git diff --quiet; then
          echo "No changes detected. Exiting."
          exit 0
        fi

    # Debug Git status to ensure everything is in place
    - name: Debug Git Status
      run: |
        git status
        git log -3 --oneline
        git remote -v
        git branch -vv

    # Push the changes to the fork repository
    - name: Push Branch to Fork
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push -u origin update-from-upstream || echo "No changes to push."

    # Create a pull request if there are changes to merge
    - name: Create Pull Request
      if: success()
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Sync changes from upstream"
        branch: update-from-upstream


 
