name: Auto-Sync Fork

on:
  schedule:
    - cron: "*/5 * * * *" 
  workflow_dispatch: # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Fork Repository
      uses: actions/checkout@v4
      with:
        ref: main 
    - name: Configure Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"

    - name: Add Upstream Repository
      run: |
        git remote | grep upstream || git remote add upstream https://github.com/Vishu-Organization/FlavorHive
        git fetch upstream

    - name: Merge Changes from Upstream
      run: |
       git merge upstream/main --no-edit --allow-unrelated-histories --strategy=recursive --strategy-option=theirs || echo "No changes to merge."

    - name: Push Changes to Fork
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin main
