name: Auto-Sync Fork

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes (adjust as needed)
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Fork Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"

    - name: Add Upstream Repository
      run: |
        if ! git remote | grep -q upstream; then
          git remote add upstream https://github.com/Vishu-Organization/FlavorHive
        fi
        git fetch upstream

    - name: Create Branch for Upstream Changes
      run: |
        git fetch upstream
        git checkout -B update-from-upstream origin/main
        git merge upstream/main --no-edit --allow-unrelated-histories || {
          echo "Merge failed, attempting a reset.";
          git reset --hard upstream/main
        }

    - name: Debug Git Status
      run: |
        git status
        git log -3 --oneline
        git remote -v
        git branch -vv

    - name: Push Branch to Fork
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push -u origin update-from-upstream || echo "No changes to push."

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Sync changes from upstream"
        branch: update-from-upstream
        base: main
        title: "Merge Updates from Upstream"
        body: |
          This pull request merges changes from the upstream repository into the fork.
        labels: "sync"
        committer: GitHub <noreply@github.com>
        author: 14vasudha <14vasudha@users.noreply.github.com>
        signoff: false
        delete-branch: true
        draft: false
