name: Auto-Sync Fork

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Fork Repository
      uses: actions/checkout@v4
      with:
        ref: main 
    - name: Configure Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"

    - name: Add Upstream Repository
      run: |
        git remote | grep upstream || git remote add upstream https://github.com/Vishu-Organization/FlavorHive
        git fetch upstream

    - name: Create Branch for Upstream Changes
      run: |
        git checkout -b update-from-upstream
        git merge upstream/main --no-edit --allow-unrelated-histories --strategy=recursive --strategy-option=theirs || echo "No changes to merge."

    - name: Push Branch to Fork
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push -u origin update-from-upstream || echo "No changes to push."

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Merge updates from upstream"
        branch: update-from-upstream
        title: "Sync with Upstream Repository"
        body: |
          This PR syncs the fork with the upstream repository.
