name: Sync Upstream

on:
  schedule:
    - cron: "*/5 * * * *"
    
permissions:
  contents: write
  pull-requests: write


jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git remote add upstream https://github.com/Vishu-Organization/FlavorHive
          git fetch upstream

      - name: Check for updates and create PR
        run: |
          if [ "$(git rev-parse HEAD)" != "$(git rev-parse upstream/main)" ]; then
              TIMESTAMP=$(date +%Y%m%d%H%M%S)
              UPDATE_BRANCH="update-from-upstream-$TIMESTAMP"
              git checkout -b "$UPDATE_BRANCH"
              git merge upstream/main --no-edit
              git push origin "$UPDATE_BRANCH"
              gh pr create --title "Sync from upstream" \
                           --body "This PR syncs changes from the upstream repository." \
                           --head "$UPDATE_BRANCH" \
                           --base main
          else
              echo "No updates from upstream."
          fi
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
