name: Sync Upstream

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes (adjust as needed)
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git remote add upstream https://github.com/Vishu-Organization/FlavorHive
          git fetch upstream

      - name: Check for updates
        id: check_updates
        run: |
          if [ "$(git rev-parse HEAD)" != "$(git rev-parse upstream/main)" ]; then
              echo "has_updates=true" >> $GITHUB_ENV
          else
              echo "has_updates=false" >> $GITHUB_ENV
          fi

      - name: Create a new branch and sync changes
        if: env.has_updates == 'true'
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          UPDATE_BRANCH="update-from-upstream-$TIMESTAMP"
          git checkout -b "$UPDATE_BRANCH"
          git merge upstream/main --no-edit
          git push origin "$UPDATE_BRANCH"

      - name: Create Pull Request
        if: env.has_updates == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Sync changes from upstream"
          branch: ${{ steps.create_branch.outputs.branch }}
          title: "Sync from upstream"
          body: "This PR syncs changes from the upstream repository."
          base: main
          labels: "sync"

