name: Auto-Sync Fork

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes (adjust as needed)
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Fork Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"

    - name: Add Upstream Repository
      run: |
        if ! git remote | grep -q upstream; then
          git remote add upstream https://github.com/Vishu-Organization/FlavorHive
        fi
        git fetch upstream

    - name: Create Branch for Upstream Changes
      run: |
        git fetch upstream
        git checkout -B update-from-upstream origin/main
        git merge upstream/main --no-edit --allow-unrelated-histories || {
          echo "Merge failed, attempting a reset.";
          git reset --hard upstream/main
        }

    - name: Debug Git Status
      run: |
        git status
        git log -3 --oneline
        git remote -v
        git branch -vv

    - name: Push Branch to Fork
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push --set-upstream origin update-from-upstream || echo "No changes to push."

    - name: Check for updates and create PR
      run: |
          if [ "$(git rev-parse HEAD)" != "$(git rev-parse upstream/main)" ]; then
              TIMESTAMP=$(date +%Y%m%d%H%M%S)
              UPDATE_BRANCH="update-from-upstream-$TIMESTAMP"
              git checkout -b "$UPDATE_BRANCH"
              git merge upstream/main --no-edit
              git push origin "$UPDATE_BRANCH"
              gh pr create --title "Sync from upstream" \
                           --body "This PR syncs changes from the upstream repository." \
                           --head "$UPDATE_BRANCH" \
                           --base main
          else
              echo "No updates from upstream."
          fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
